### ISSUE TITLE
Configure to show alpha updates if I'm already on alpha?

### ISSUE THREAD

**Issue by ColtonIdle** [janderssonse/gradle-versions-filter-plugin#4]
Something that happens a lot is that I have alpha dependencies and they go to beta or they go to alphax+1, but they don't show in the list because stable is there. How can I configure this to show me newer versions of the dependency if I'm already on alpha.

**Comment by janderssonse** [comment]
Sorry for the late reply. I added an example in the [README](https://github.com/janderssonse/gradle-versions-filter-plugin/blob/main/README.md#example-configuration) which I think should do what you wanted. As you see, alpha, beta etc is per default not considered, but see the example for how you could let these be considered. Or did you go for configuring the original plugin?

**Comment by janderssonse** [comment]
Closing this as there is an example in the readme.
