### ISSUE TITLE
Ability to Extend Defaults

### ISSUE THREAD

**Issue by Fleshgrinder** [janderssonse/gradle-versions-filter-plugin#7]
The plugin is currently written in a way that both the inclusions and exclusions cannot be kept and extended. Instead one has to redefine them entirely if an additional pattern is to be added. This is because the qualifiers are hardcoded in the plugin, and applied only if the list is not empty. It would be better to switch to Gradle's property API in the extension, with the defaults already added. This way users can decide if they want to add or set.

I'm happy to provide a patch, but once I'm back from holiday's in January. 😉

**Comment by janderssonse** [comment]
Thanks for the input, good suggestions. I'll have a look at that after the holidays:)

**Comment by janderssonse** [comment]
Had a long holiday:) I implemented this partially in 0.1.12.
Lazy properties, that is set default if no options given.
