### ISSUE TITLE
Filter is dropped if any other rule is added to the original plugin

### ISSUE THREAD

**Issue by Fleshgrinder** [janderssonse/gradle-versions-filter-plugin#8]
I tried to work around https://github.com/janderssonse/gradle-versions-filter-plugin/issues/7 by using …

```kotlin
tasks.dependencyUpdates {
    checkConstraints = true
    rejectVersionIf { /* custom code */ }
}
```

… but the instant I apply this all the rules of this plugin are ignored. I could not figure out why by simply looking at the sources here at GitHub, but I assume it is something trivial. Again, happy to provide a pull request, but only after holidays. 🎅

**Comment by janderssonse** [comment]
Almost all original options are now forwarded to real upstreams plugin. Your use cases should be covered by 0.1.12, 0.1.13, albeit with a slightly different syntax. See the README for clearer description. 

Thanks for your suggestions!
